// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.13.0
//  VPP:              unknown

// Package probe contains generated bindings for API file probe.api.
//
// Contents:
// -  6 messages
package probe

import (
	ip_types "github.com/fivetime/sbw-limiter/internal/binapi/ip_types"
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "probe"
	APIVersion = "0.1.0"
	VersionCrc = 0x9327f437
)

// Batch point-lookup of classify sessions in ONE table by match key.
//
//	Resolves each key to the hit-next index installed on its classify session
//	(the policer index in policer-classify mode), or ~0 if no session matches.
//	This is the O(1)-per-key alternative to a whole-table classify_session_dump
//	on the incremental reconcile hot path: each key is a single hash lookup —
//	exactly the one the data plane does per packet (vnet_classify_find_entry) —
//	so a member add/remove costs O(pool) point lookups instead of dumping the
//	edge-wide shared mask table. The handler runs on the main thread, serialized
//	with classify_add_del_session writes, and passes now=0 so it never mutates
//	the entry's hit counter / last_heard.
//	All keys in one request share ONE table (hence one key_len), because a
//	classify table's match buffer length is fixed by its mask. The caller groups
//	its keys by mask/table and issues one request per table.
//	- table_id - the classify table to look up in
//	- key_len  - bytes per key = (skip_n_vectors + match_n_vectors) * 16 for
//	                  this table (same full match buffer classify_add_del_session
//	                  takes: skip vectors + match vectors, address at its absolute
//	                  packet offset)
//	- match_len - total bytes in <match> = count * key_len
//	- match     - the keys, concatenated (count of them = match_len/key_len)
//
// ProbeClassifyLookup defines message 'probe_classify_lookup'.
type ProbeClassifyLookup struct {
	TableID  uint32 `binapi:"u32,name=table_id" json:"table_id,omitempty"`
	KeyLen   uint32 `binapi:"u32,name=key_len" json:"key_len,omitempty"`
	MatchLen uint32 `binapi:"u32,name=match_len" json:"-"`
	Match    []byte `binapi:"u8[match_len],name=match" json:"match,omitempty"`
}

func (m *ProbeClassifyLookup) Reset()               { *m = ProbeClassifyLookup{} }
func (*ProbeClassifyLookup) GetMessageName() string { return "probe_classify_lookup" }
func (*ProbeClassifyLookup) GetCrcString() string   { return "63ac8370" }
func (*ProbeClassifyLookup) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *ProbeClassifyLookup) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4                // m.TableID
	size += 4                // m.KeyLen
	size += 4                // m.MatchLen
	size += 1 * len(m.Match) // m.Match
	return size
}
func (m *ProbeClassifyLookup) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.TableID)
	buf.EncodeUint32(m.KeyLen)
	buf.EncodeUint32(uint32(len(m.Match)))
	buf.EncodeBytes(m.Match, 0)
	return buf.Bytes(), nil
}
func (m *ProbeClassifyLookup) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.TableID = buf.DecodeUint32()
	m.KeyLen = buf.DecodeUint32()
	m.MatchLen = buf.DecodeUint32()
	m.Match = make([]byte, m.MatchLen)
	copy(m.Match, buf.DecodeBytes(len(m.Match)))
	return nil
}

// Reply to probe_classify_lookup.
//   - count - number of results (== request count), positionally aligned
//   - hits  - per-key hit-next index, or ~0 (0xffffffff) if not found
//
// ProbeClassifyLookupReply defines message 'probe_classify_lookup_reply'.
type ProbeClassifyLookupReply struct {
	Retval int32    `binapi:"i32,name=retval" json:"retval,omitempty"`
	Count  uint32   `binapi:"u32,name=count" json:"-"`
	Hits   []uint32 `binapi:"u32[count],name=hits" json:"hits,omitempty"`
}

func (m *ProbeClassifyLookupReply) Reset()               { *m = ProbeClassifyLookupReply{} }
func (*ProbeClassifyLookupReply) GetMessageName() string { return "probe_classify_lookup_reply" }
func (*ProbeClassifyLookupReply) GetCrcString() string   { return "c98ec7b7" }
func (*ProbeClassifyLookupReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *ProbeClassifyLookupReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4               // m.Retval
	size += 4               // m.Count
	size += 4 * len(m.Hits) // m.Hits
	return size
}
func (m *ProbeClassifyLookupReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint32(uint32(len(m.Hits)))
	for i := 0; i < len(m.Hits); i++ {
		var x uint32
		if i < len(m.Hits) {
			x = uint32(m.Hits[i])
		}
		buf.EncodeUint32(x)
	}
	return buf.Bytes(), nil
}
func (m *ProbeClassifyLookupReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.Count = buf.DecodeUint32()
	m.Hits = make([]uint32, m.Count)
	for i := 0; i < len(m.Hits); i++ {
		m.Hits[i] = buf.DecodeUint32()
	}
	return nil
}

// Add or remove a FIB-reachability probe target.
//
//	The plugin periodically resolves <prefix> in FIB table <table_id> and
//	publishes the verdict to /probe/fib/<name>/{reachable,dpo_type,changes}.
//	- is_add - add (1) or remove (0)
//	- table_id - IP4/IP6 FIB table id (VRF), family taken from prefix
//	- prefix - the target prefix (typically a /32 or /128 next-hop)
//	- name - stats-segment name for this target (unique)
//
// ProbeFibAddDel defines message 'probe_fib_add_del'.
type ProbeFibAddDel struct {
	IsAdd   bool            `binapi:"bool,name=is_add" json:"is_add,omitempty"`
	TableID uint32          `binapi:"u32,name=table_id" json:"table_id,omitempty"`
	Prefix  ip_types.Prefix `binapi:"prefix,name=prefix" json:"prefix,omitempty"`
	Name    string          `binapi:"string[64],name=name" json:"name,omitempty"`
}

func (m *ProbeFibAddDel) Reset()               { *m = ProbeFibAddDel{} }
func (*ProbeFibAddDel) GetMessageName() string { return "probe_fib_add_del" }
func (*ProbeFibAddDel) GetCrcString() string   { return "6c72341e" }
func (*ProbeFibAddDel) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *ProbeFibAddDel) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1      // m.IsAdd
	size += 4      // m.TableID
	size += 1      // m.Prefix.Address.Af
	size += 1 * 16 // m.Prefix.Address.Un
	size += 1      // m.Prefix.Len
	size += 64     // m.Name
	return size
}
func (m *ProbeFibAddDel) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeBool(m.IsAdd)
	buf.EncodeUint32(m.TableID)
	buf.EncodeUint8(uint8(m.Prefix.Address.Af))
	buf.EncodeBytes(m.Prefix.Address.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(m.Prefix.Len)
	buf.EncodeString(m.Name, 64)
	return buf.Bytes(), nil
}
func (m *ProbeFibAddDel) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeBool()
	m.TableID = buf.DecodeUint32()
	m.Prefix.Address.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.Prefix.Address.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.Prefix.Len = buf.DecodeUint8()
	m.Name = buf.DecodeString(64)
	return nil
}

// ProbeFibAddDelReply defines message 'probe_fib_add_del_reply'.
type ProbeFibAddDelReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *ProbeFibAddDelReply) Reset()               { *m = ProbeFibAddDelReply{} }
func (*ProbeFibAddDelReply) GetMessageName() string { return "probe_fib_add_del_reply" }
func (*ProbeFibAddDelReply) GetCrcString() string   { return "e8d4e804" }
func (*ProbeFibAddDelReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *ProbeFibAddDelReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *ProbeFibAddDelReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *ProbeFibAddDelReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// ProbeFibDetails defines message 'probe_fib_details'.
type ProbeFibDetails struct {
	TableID   uint32          `binapi:"u32,name=table_id" json:"table_id,omitempty"`
	Prefix    ip_types.Prefix `binapi:"prefix,name=prefix" json:"prefix,omitempty"`
	Name      string          `binapi:"string[64],name=name" json:"name,omitempty"`
	Reachable uint8           `binapi:"u8,name=reachable" json:"reachable,omitempty"`
	DpoType   uint8           `binapi:"u8,name=dpo_type" json:"dpo_type,omitempty"`
}

func (m *ProbeFibDetails) Reset()               { *m = ProbeFibDetails{} }
func (*ProbeFibDetails) GetMessageName() string { return "probe_fib_details" }
func (*ProbeFibDetails) GetCrcString() string   { return "7a55763a" }
func (*ProbeFibDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *ProbeFibDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4      // m.TableID
	size += 1      // m.Prefix.Address.Af
	size += 1 * 16 // m.Prefix.Address.Un
	size += 1      // m.Prefix.Len
	size += 64     // m.Name
	size += 1      // m.Reachable
	size += 1      // m.DpoType
	return size
}
func (m *ProbeFibDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.TableID)
	buf.EncodeUint8(uint8(m.Prefix.Address.Af))
	buf.EncodeBytes(m.Prefix.Address.Un.XXX_UnionData[:], 16)
	buf.EncodeUint8(m.Prefix.Len)
	buf.EncodeString(m.Name, 64)
	buf.EncodeUint8(m.Reachable)
	buf.EncodeUint8(m.DpoType)
	return buf.Bytes(), nil
}
func (m *ProbeFibDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.TableID = buf.DecodeUint32()
	m.Prefix.Address.Af = ip_types.AddressFamily(buf.DecodeUint8())
	copy(m.Prefix.Address.Un.XXX_UnionData[:], buf.DecodeBytes(16))
	m.Prefix.Len = buf.DecodeUint8()
	m.Name = buf.DecodeString(64)
	m.Reachable = buf.DecodeUint8()
	m.DpoType = buf.DecodeUint8()
	return nil
}

// Dump the registered FIB-reachability probe targets + last verdicts.
// ProbeFibDump defines message 'probe_fib_dump'.
type ProbeFibDump struct{}

func (m *ProbeFibDump) Reset()               { *m = ProbeFibDump{} }
func (*ProbeFibDump) GetMessageName() string { return "probe_fib_dump" }
func (*ProbeFibDump) GetCrcString() string   { return "51077d14" }
func (*ProbeFibDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *ProbeFibDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *ProbeFibDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *ProbeFibDump) Unmarshal(b []byte) error {
	return nil
}

func init() { file_probe_binapi_init() }
func file_probe_binapi_init() {
	api.RegisterMessage((*ProbeClassifyLookup)(nil), "probe_classify_lookup_63ac8370")
	api.RegisterMessage((*ProbeClassifyLookupReply)(nil), "probe_classify_lookup_reply_c98ec7b7")
	api.RegisterMessage((*ProbeFibAddDel)(nil), "probe_fib_add_del_6c72341e")
	api.RegisterMessage((*ProbeFibAddDelReply)(nil), "probe_fib_add_del_reply_e8d4e804")
	api.RegisterMessage((*ProbeFibDetails)(nil), "probe_fib_details_7a55763a")
	api.RegisterMessage((*ProbeFibDump)(nil), "probe_fib_dump_51077d14")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*ProbeClassifyLookup)(nil),
		(*ProbeClassifyLookupReply)(nil),
		(*ProbeFibAddDel)(nil),
		(*ProbeFibAddDelReply)(nil),
		(*ProbeFibDetails)(nil),
		(*ProbeFibDump)(nil),
	}
}
