// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package probe

import (
	"context"
	"fmt"
	"io"

	memclnt "github.com/fivetime/sbw-limiter/internal/binapi/memclnt"
	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service probe.
type RPCService interface {
	ProbeClassifyLookup(ctx context.Context, in *ProbeClassifyLookup) (*ProbeClassifyLookupReply, error)
	ProbeFibAddDel(ctx context.Context, in *ProbeFibAddDel) (*ProbeFibAddDelReply, error)
	ProbeFibDump(ctx context.Context, in *ProbeFibDump) (RPCService_ProbeFibDumpClient, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) ProbeClassifyLookup(ctx context.Context, in *ProbeClassifyLookup) (*ProbeClassifyLookupReply, error) {
	out := new(ProbeClassifyLookupReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) ProbeFibAddDel(ctx context.Context, in *ProbeFibAddDel) (*ProbeFibAddDelReply, error) {
	out := new(ProbeFibAddDelReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) ProbeFibDump(ctx context.Context, in *ProbeFibDump) (RPCService_ProbeFibDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_ProbeFibDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_ProbeFibDumpClient interface {
	Recv() (*ProbeFibDetails, error)
	api.Stream
}

type serviceClient_ProbeFibDumpClient struct {
	api.Stream
}

func (c *serviceClient_ProbeFibDumpClient) Recv() (*ProbeFibDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *ProbeFibDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}
