// Package binapi groups the VPP binary-API Go bindings generated from the
// VPP master .api files (T-204) — the version the edge runs (ghcr.io/fivetime/
// vpp:master, FDio/vpp master). Subpackages are generated by binapi-generator
// (kept in sync with go.mod's go.fd.io/govpp) and MUST NOT be edited by hand —
// regenerate via scripts/gen-binapi.sh.
//
// Only the dependency closure of the plugins the edge-agent uses is kept:
// policer, classify (incl. policer_classify), abf, acl, urpf, lcp (linux-cp),
// plus their shared type packages (ip_types, interface_types, fib_types,
// ethernet_types, policer_types, acl_types, memclnt).
//
// The agent materializers (T-402/T-403/T-407/T-408/T-410) call these through
// govpp's binapi channel; T-401 owns the connection.
package binapi

// VPPVersion is the VPP release the bindings were generated against. Keep in
// sync with scripts/gen-binapi.sh and the edge VPP build (DESIGN.md §1).
const VPPVersion = "master (FDio/vpp @458e2ee65; ghcr.io/fivetime/vpp:master, the version the edge runs)"
